# coding: utf-8

"""
    猎萝卜开放平台

    猎萝卜开放平台  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MakeOrderRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'company_id': 'str',
        'mobile': 'str',
        'job_id': 'str',
        'candidate': 'AllOfMakeOrderRequestCandidate'
    }

    attribute_map = {
        'company_id': 'companyId',
        'mobile': 'mobile',
        'job_id': 'jobId',
        'candidate': 'candidate'
    }

    def __init__(self, company_id=None, mobile=None, job_id=None, candidate=None):  # noqa: E501
        """MakeOrderRequest - a model defined in Swagger"""  # noqa: E501
        self._company_id = None
        self._mobile = None
        self._job_id = None
        self._candidate = None
        self.discriminator = None
        if company_id is not None:
            self.company_id = company_id
        if mobile is not None:
            self.mobile = mobile
        if job_id is not None:
            self.job_id = job_id
        if candidate is not None:
            self.candidate = candidate

    @property
    def company_id(self):
        """Gets the company_id of this MakeOrderRequest.  # noqa: E501

        公司唯一ID  # noqa: E501

        :return: The company_id of this MakeOrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """Sets the company_id of this MakeOrderRequest.

        公司唯一ID  # noqa: E501

        :param company_id: The company_id of this MakeOrderRequest.  # noqa: E501
        :type: str
        """

        self._company_id = company_id

    @property
    def mobile(self):
        """Gets the mobile of this MakeOrderRequest.  # noqa: E501

        用户手机号  # noqa: E501

        :return: The mobile of this MakeOrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._mobile

    @mobile.setter
    def mobile(self, mobile):
        """Sets the mobile of this MakeOrderRequest.

        用户手机号  # noqa: E501

        :param mobile: The mobile of this MakeOrderRequest.  # noqa: E501
        :type: str
        """

        self._mobile = mobile

    @property
    def job_id(self):
        """Gets the job_id of this MakeOrderRequest.  # noqa: E501

        职位ID  # noqa: E501

        :return: The job_id of this MakeOrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this MakeOrderRequest.

        职位ID  # noqa: E501

        :param job_id: The job_id of this MakeOrderRequest.  # noqa: E501
        :type: str
        """

        self._job_id = job_id

    @property
    def candidate(self):
        """Gets the candidate of this MakeOrderRequest.  # noqa: E501


        :return: The candidate of this MakeOrderRequest.  # noqa: E501
        :rtype: AllOfMakeOrderRequestCandidate
        """
        return self._candidate

    @candidate.setter
    def candidate(self, candidate):
        """Sets the candidate of this MakeOrderRequest.


        :param candidate: The candidate of this MakeOrderRequest.  # noqa: E501
        :type: AllOfMakeOrderRequestCandidate
        """

        self._candidate = candidate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MakeOrderRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MakeOrderRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
