# coding: utf-8

"""
    猎萝卜开放平台

    猎萝卜开放平台  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Project(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'started_at': 'date',
        'ended_at': 'date',
        'name': 'str',
        'org_name': 'str',
        'position': 'str',
        'description': 'str'
    }

    attribute_map = {
        'started_at': 'startedAt',
        'ended_at': 'endedAt',
        'name': 'name',
        'org_name': 'orgName',
        'position': 'position',
        'description': 'description'
    }

    def __init__(self, started_at=None, ended_at=None, name=None, org_name=None, position=None, description=None):  # noqa: E501
        """Project - a model defined in Swagger"""  # noqa: E501
        self._started_at = None
        self._ended_at = None
        self._name = None
        self._org_name = None
        self._position = None
        self._description = None
        self.discriminator = None
        if started_at is not None:
            self.started_at = started_at
        if ended_at is not None:
            self.ended_at = ended_at
        if name is not None:
            self.name = name
        if org_name is not None:
            self.org_name = org_name
        if position is not None:
            self.position = position
        if description is not None:
            self.description = description

    @property
    def started_at(self):
        """Gets the started_at of this Project.  # noqa: E501

        开始日期  # noqa: E501

        :return: The started_at of this Project.  # noqa: E501
        :rtype: date
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this Project.

        开始日期  # noqa: E501

        :param started_at: The started_at of this Project.  # noqa: E501
        :type: date
        """

        self._started_at = started_at

    @property
    def ended_at(self):
        """Gets the ended_at of this Project.  # noqa: E501

        结束日期  # noqa: E501

        :return: The ended_at of this Project.  # noqa: E501
        :rtype: date
        """
        return self._ended_at

    @ended_at.setter
    def ended_at(self, ended_at):
        """Sets the ended_at of this Project.

        结束日期  # noqa: E501

        :param ended_at: The ended_at of this Project.  # noqa: E501
        :type: date
        """

        self._ended_at = ended_at

    @property
    def name(self):
        """Gets the name of this Project.  # noqa: E501

        项目名称  # noqa: E501

        :return: The name of this Project.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Project.

        项目名称  # noqa: E501

        :param name: The name of this Project.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def org_name(self):
        """Gets the org_name of this Project.  # noqa: E501

        公司名称  # noqa: E501

        :return: The org_name of this Project.  # noqa: E501
        :rtype: str
        """
        return self._org_name

    @org_name.setter
    def org_name(self, org_name):
        """Sets the org_name of this Project.

        公司名称  # noqa: E501

        :param org_name: The org_name of this Project.  # noqa: E501
        :type: str
        """

        self._org_name = org_name

    @property
    def position(self):
        """Gets the position of this Project.  # noqa: E501

        职位  # noqa: E501

        :return: The position of this Project.  # noqa: E501
        :rtype: str
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this Project.

        职位  # noqa: E501

        :param position: The position of this Project.  # noqa: E501
        :type: str
        """

        self._position = position

    @property
    def description(self):
        """Gets the description of this Project.  # noqa: E501

        项目介绍  # noqa: E501

        :return: The description of this Project.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Project.

        项目介绍  # noqa: E501

        :param description: The description of this Project.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Project, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Project):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
