# coding: utf-8

"""
    猎萝卜开放平台

    猎萝卜开放平台  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import lieluobo
from lieluobo.models.bind_state import BindState  # noqa: E501
from lieluobo.rest import ApiException


class TestBindState(unittest.TestCase):
    """BindState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBindState(self):
        """Test BindState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lieluobo.models.bind_state.BindState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
