# coding: utf-8

"""
    猎萝卜开放平台

    猎萝卜开放平台  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import lieluobo
from lieluobo.models.all_of_education_degree import AllOfEducationDegree  # noqa: E501
from lieluobo.rest import ApiException


class TestAllOfEducationDegree(unittest.TestCase):
    """AllOfEducationDegree unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfEducationDegree(self):
        """Test AllOfEducationDegree"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lieluobo.models.all_of_education_degree.AllOfEducationDegree()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
