# coding: utf-8

"""
    猎萝卜开放平台

    猎萝卜开放平台  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest
from lieluobo.models import Company, User
from lieluobo.api.bind_api import BindApi
from lieluobo.configuration import Configuration
from lieluobo.api_client import ApiClient
from lieluobo.authenticator import ApiKeyAuthenticator
from lieluobo.rest import ApiException


class TestBindApi(unittest.TestCase):
    """BindApi unit test stubs"""

    def setUp(self):
        # API 地址
        self.host = 'http://127.0.0.1:9090'

        # 密钥对
        self.secret_id = '8f7d34289a81497a852f1691487a1967'
        self.secret_key = 'IYM28RgoqRc5XLmmamH7JFLU6AxWwvs0'

        self.company_id = 'leicptih5gop0'

    def tearDown(self):
        pass

    # 创建API实例
    @property
    def api(self):
        configuration = Configuration()
        configuration.host = self.host
        configuration.authenticate = ApiKeyAuthenticator(self.secret_id, self.secret_key)
        configuration.debug = True
        return BindApi(api_client=ApiClient(configuration))

    # 绑定公司
    def test_bind_company(self):
        company = Company(unique_id=self.company_id,
                          name='来自谷露的公司2',
                          license_no='91310000093856237U',
                          contact_name='某小弟',
                          contact_mobile='18662203613',
                          notify_url='https://callback.xxx.com/company')
        resp = self.api.bind_company(body=company)
        self.assertEqual(resp.unique_id, company.unique_id)

    # 获取公司信息
    def test_get_company(self):
        company = self.api.get_company(self.company_id)
        self.assertEqual(company.unique_id, self.company_id)

    # 绑定账号
    def test_bind_user(self):
        user = User(mobile='18662203615',
                    name='某小弟',
                    company_id=self.company_id,
                    notify_url='https://callback.xxx.com/user')
        resp = self.api.bind_user(body=user)
        self.assertEqual(resp.mobile, user.mobile)

    # 获取用户信息
    def test_get_user(self):
        user = self.api.get_user(unique_id=self.company_id, mobile='18662203615')
        self.assertEqual(user.mobile, '18662203615')
        return user


if __name__ == '__main__':
    unittest.main()
