# coding: utf-8

"""
    猎萝卜开放平台

    猎萝卜开放平台  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import lieluobo
from lieluobo.models.credential import Credential  # noqa: E501
from lieluobo.rest import ApiException


class TestCredential(unittest.TestCase):
    """Credential unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCredential(self):
        """Test Credential"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lieluobo.models.credential.Credential()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
