# coding: utf-8

"""
    猎萝卜开放平台

    猎萝卜开放平台  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import lieluobo
from lieluobo import Configuration, ApiClient
from lieluobo.api.redirect_api import RedirectApi  # noqa: E501
from lieluobo.authenticator import ApiKeyAuthenticator
from lieluobo.rest import ApiException


class TestRedirectApi(unittest.TestCase):
    """RedirectApi unit test stubs"""

    def setUp(self):
        # API 地址
        self.host = 'http://127.0.0.1:9090'

        # 密钥对
        self.secret_id = '8f7d34289a81497a852f1691487a1967'
        self.secret_key = 'IYM28RgoqRc5XLmmamH7JFLU6AxWwvs0'

    # 创建API实例
    @property
    def api(self):
        configuration = Configuration()
        configuration.host = self.host
        configuration.authenticate = ApiKeyAuthenticator(self.secret_id, self.secret_key)
        return RedirectApi(api_client=ApiClient(configuration))  # noqa: E501

    def tearDown(self):
        pass

    def test_get_token(self):
        token = self.api.get_token(company_id='leicptih5gop0', mobile='18662203615')
        print(token)


if __name__ == '__main__':
    unittest.main()
