# coding: utf-8

"""
    猎萝卜开放平台

    猎萝卜开放平台  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import lieluobo
from lieluobo import Configuration, ApiClient, Candidate, Gender, Experience, Education, Degree, Project
from lieluobo.api.recommend_api import RecommendApi  # noqa: E501
from lieluobo.authenticator import ApiKeyAuthenticator
from lieluobo.rest import ApiException


class TestRecommendApi(unittest.TestCase):
    """RecommendApi unit test stubs"""

    def setUp(self):
        # API 地址
        self.host = 'http://127.0.0.1:9090'

        # 密钥对
        self.secret_id = '8f7d34289a81497a852f1691487a1967'
        self.secret_key = 'IYM28RgoqRc5XLmmamH7JFLU6AxWwvs0'

    # 创建API实例
    @property
    def api(self):
        configuration = Configuration()
        configuration.host = self.host
        configuration.authenticate = ApiKeyAuthenticator(self.secret_id, self.secret_key)
        return RecommendApi(api_client=ApiClient(configuration))  # noqa: E501

    def tearDown(self):
        pass

    def test_authorize(self):
        candidate = Candidate(
            unique_id='leicptih5gop0',
            notify_url='https://callback.xxx.com/candidate',
            location='上海',
            intended_industries=['互联网/软件/服务'],
            gender=Gender.MALE,
            birthday='1984-01-02',
            salary=455000,
            experiences=[
                Experience(
                    org_name='北京喜宝动力网络技术股份有限公司',
                    dept_name='产品部',
                    started_at='2017-09-01',
                    in_service=True,
                    position='产品副总监',
                    description='全面负责公司电商广告产品线工作，产品规划、目标制定、发展路线、组建及管理团队、产品设计及管理、客户解决方案、用户体验、产品商业化路线、运营数据、运营策略、产品培训、宣讲，商务技术支持，对公司电商广告线所有产品负责。'
                ),
                Experience(
                    org_name='百变空间',
                    position='高级产品经理',
                    started_at='2016-10-01',
                    ended_at='2017-09-01',
                    in_service=True,
                    description='''1. 负责挖掘整理需求，市场调研与竞品分析，产品设计和策略调优。主要负责订单派发、订单跟踪和监督、结算锁定与解锁、售后服务、百变基金管理、诚信体系、智能家居场景挖掘和设计等模块。
2. 负责产品功能设计、交互设计，把控业务流程，制定产品评定指标。
3. 制定产品计划和发布周期，对产品的各阶段进行高效的管理，与团队内运营、开发、测试高效沟通，推动项目落地，确保项目按时上线，负责拉新和粘性维护。
4. 收集分析产品数据，挖掘产品优化迭代策略和方向，不断提升用户体验，提升用户的活跃度。1. 负责挖掘整理需求，市场调研与竞品分析，产品设计和策略调优。主要负责订单派发、订单跟踪和监督、结算锁定与解锁、售后服务、百变基金管理、诚信体系、智能家居场景挖掘和设计等模块。
2. 负责产品功能设计、交互设计，把控业务流程，制定产品评定指标。
3. 制定产品计划和发布周期，对产品的各阶段进行高效的管理，与团队内运营、开发、测试高效沟通，推动项目落地，确保项目按时上线，负责拉新和粘性维护。
4. 收集分析产品数据，挖掘产品优化迭代策略和方向，不断提升用户体验，提升用户的活跃度。'''
                )
            ],
            educations=[
                Education(
                    school='哈尔滨工业大学',
                    major='电子与通信工程',
                    degree=Degree.MASTER,
                    started_at='2009-04-01',
                    ended_at='2011-06-30'
                ),
                Education(
                    school='哈尔滨理工大学',
                    major='电子信息工程',
                    degree=Degree.BACHELOR,
                    started_at='2004-09-01',
                    ended_at='2008-07-01'
                )
            ],
            projects=[
                Project(
                    org_name='北京喜宝动力网络技术股份有限公司',
                    name='京东app 云crm + ai数据工厂+ 电商广告 +社交电商 会员中心',
                    position='产品副总监',
                    started_at='2018-10-01',
                    description='''JD 品牌对会员的沉淀管理能力较弱，同时缺乏数据指导能力，也不能针对不同分群会员进行个性化广告触达。没有驱动消费者总资产最大化转化的机制。同时品牌有社交裂变传播的强需求。
项目目标： 实现品牌对自有会员的精细化管理，搭建品牌私有云CRM和JD 数坊，赋能品牌透视全链路数据的能力、人群画像分群能力、会员画像定向触达能力、会员私域沉淀能力、社交裂变拓展品牌边界能力。
B端用户规模2000+,C端用户规模1亿+
解决方案： 私有云CRM(解决存量会员沉淀和管理） + AI数据能力（解决会员数据融合、画像及标签加工，数据赋能品牌资产最大化转化） + 私域小程序社交裂变（解决品牌增量会员及数据资产归属） + 广告触达（解决品牌消费者资产最大化）
产品架构：
上层社交裂变层： 激励机制、小程序流量裂变，CPS拼团广告联盟
上层数据应用层： 品牌个性化定制功能模块，如积分兑换、抽奖、拼团、专享折扣、分享有礼等，支持会员定向。
中台广告数据层： 对接DMP进行广告投放、短信触达、微信触达；广告投放效果评估
中台数据加工层： 以数据挖掘、机器学习、深度学习等进行会员画像、人群标签及聚类、消费预估等
底层会员数据层： 底层会员信息层、云CRM融合多维会员基本信息、消费行为信息、站外微信、头条等信息
底层品牌入驻层： 品牌入驻、登录、充值、数据报表等
1. 产品架构规划及解决方案制定包括产品生命周期管理、团队管理
2. 人群画像、聚类、海量数据价值挖掘，品牌定制化人群能力
3. 大数据透视和分析及展示，赋能品牌数据驱动能力
4. B端个性化功能模块设计、会员增长、CPS拼团广告联盟体系设计、C端首页组合模块设计
5. 会员积分体系搭建和会员层级规则制定'''
                )
            ]
        )

        self.api.authorize(body=[candidate])

    def test_get_recommend_jobs(self):
        jobs = self.api.get_recommend_jobs('leicptih5gop0')
        print(jobs)


if __name__ == '__main__':
    unittest.main()
