# coding: utf-8

"""
    猎萝卜开放平台

    猎萝卜开放平台  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import lieluobo
from lieluobo.models.order_state import OrderState  # noqa: E501
from lieluobo.rest import ApiException


class TestOrderState(unittest.TestCase):
    """OrderState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderState(self):
        """Test OrderState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lieluobo.models.order_state.OrderState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
