# coding: utf-8

"""
    猎萝卜开放平台

    猎萝卜开放平台  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import lieluobo
from lieluobo.api.credential_api import CredentialApi  # noqa: E501
from lieluobo.rest import ApiException


class TestCredentialApi(unittest.TestCase):
    """CredentialApi unit test stubs"""

    def setUp(self):
        self.api = CredentialApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_grant(self):
        """Test case for grant

        """
        pass

    def test_list(self):
        """Test case for list

        """
        pass

    def test_revoke(self):
        """Test case for revoke

        """
        pass


if __name__ == '__main__':
    unittest.main()
