# coding: utf-8

"""
    猎萝卜开放平台

    猎萝卜开放平台  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301
from pathlib import Path

NAME = "lieluobo"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="猎萝卜开放平台",
    author_email="",
    url="",
    keywords=["Swagger", "猎萝卜开放平台"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description=Path(__file__).joinpath('README.md').read_text(),
    long_description_content_type='text/markdown'
)
